//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BankCodeRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BankCodeRoleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Originator"/>
 *     &lt;enumeration value="Recipient"/>
 *     &lt;enumeration value="Correspondent"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BankCodeRoleType")
@XmlEnum
public enum BankCodeRoleType {


    /**
     * Auftraggeberbank
     * 
     */
    @XmlEnumValue("Originator")
    ORIGINATOR("Originator"),

    /**
     * Empfängerbank
     * 
     */
    @XmlEnumValue("Recipient")
    RECIPIENT("Recipient"),

    /**
     * Korrespondenzbank
     * 
     */
    @XmlEnumValue("Correspondent")
    CORRESPONDENT("Correspondent"),

    /**
     * andere Bankrolle
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    BankCodeRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BankCodeRoleType fromValue(String v) {
        for (BankCodeRoleType c: BankCodeRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
