//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrencyCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurrencyCode">
 *   &lt;restriction base="{urn:org:ebics:H004}CurrencyBaseType">
 *     &lt;length value="3"/>
 *     &lt;enumeration value="AFN"/>
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="AMD"/>
 *     &lt;enumeration value="ANG"/>
 *     &lt;enumeration value="AOA"/>
 *     &lt;enumeration value="ARS"/>
 *     &lt;enumeration value="AUD"/>
 *     &lt;enumeration value="AWG"/>
 *     &lt;enumeration value="AZM"/>
 *     &lt;enumeration value="BAM"/>
 *     &lt;enumeration value="BBD"/>
 *     &lt;enumeration value="BDT"/>
 *     &lt;enumeration value="BGN"/>
 *     &lt;enumeration value="BHD"/>
 *     &lt;enumeration value="BMD"/>
 *     &lt;enumeration value="BND"/>
 *     &lt;enumeration value="BOB"/>
 *     &lt;enumeration value="BRL"/>
 *     &lt;enumeration value="BSD"/>
 *     &lt;enumeration value="BTN"/>
 *     &lt;enumeration value="BWP"/>
 *     &lt;enumeration value="BYR"/>
 *     &lt;enumeration value="BZD"/>
 *     &lt;enumeration value="CAD"/>
 *     &lt;enumeration value="CDF"/>
 *     &lt;enumeration value="CHF"/>
 *     &lt;enumeration value="CLP"/>
 *     &lt;enumeration value="CNY"/>
 *     &lt;enumeration value="COP"/>
 *     &lt;enumeration value="CRC"/>
 *     &lt;enumeration value="CSD"/>
 *     &lt;enumeration value="CUP"/>
 *     &lt;enumeration value="CVE"/>
 *     &lt;enumeration value="CYP"/>
 *     &lt;enumeration value="CZK"/>
 *     &lt;enumeration value="DJV"/>
 *     &lt;enumeration value="DKK"/>
 *     &lt;enumeration value="DOP"/>
 *     &lt;enumeration value="DZD"/>
 *     &lt;enumeration value="ECS"/>
 *     &lt;enumeration value="EEK"/>
 *     &lt;enumeration value="EGP"/>
 *     &lt;enumeration value="ETB"/>
 *     &lt;enumeration value="EUR"/>
 *     &lt;enumeration value="FJD"/>
 *     &lt;enumeration value="FKP"/>
 *     &lt;enumeration value="GBP"/>
 *     &lt;enumeration value="GEL"/>
 *     &lt;enumeration value="GHC"/>
 *     &lt;enumeration value="GIP"/>
 *     &lt;enumeration value="GMD"/>
 *     &lt;enumeration value="GNF"/>
 *     &lt;enumeration value="GTQ"/>
 *     &lt;enumeration value="GYD"/>
 *     &lt;enumeration value="HKD"/>
 *     &lt;enumeration value="HNL"/>
 *     &lt;enumeration value="HRK"/>
 *     &lt;enumeration value="HTG"/>
 *     &lt;enumeration value="HUF"/>
 *     &lt;enumeration value="IDR"/>
 *     &lt;enumeration value="ILS"/>
 *     &lt;enumeration value="INR"/>
 *     &lt;enumeration value="IQD"/>
 *     &lt;enumeration value="IRR"/>
 *     &lt;enumeration value="ISK"/>
 *     &lt;enumeration value="JMD"/>
 *     &lt;enumeration value="JOD"/>
 *     &lt;enumeration value="JPY"/>
 *     &lt;enumeration value="KES"/>
 *     &lt;enumeration value="KGS"/>
 *     &lt;enumeration value="KHR"/>
 *     &lt;enumeration value="KMF"/>
 *     &lt;enumeration value="KPW"/>
 *     &lt;enumeration value="KRW"/>
 *     &lt;enumeration value="KWD"/>
 *     &lt;enumeration value="KYD"/>
 *     &lt;enumeration value="KZT"/>
 *     &lt;enumeration value="LAK"/>
 *     &lt;enumeration value="LBP"/>
 *     &lt;enumeration value="LKR"/>
 *     &lt;enumeration value="LRD"/>
 *     &lt;enumeration value="LSL"/>
 *     &lt;enumeration value="LTL"/>
 *     &lt;enumeration value="LVL"/>
 *     &lt;enumeration value="LYD"/>
 *     &lt;enumeration value="MAD"/>
 *     &lt;enumeration value="MDL"/>
 *     &lt;enumeration value="MGF"/>
 *     &lt;enumeration value="MKD"/>
 *     &lt;enumeration value="MMK"/>
 *     &lt;enumeration value="MNT"/>
 *     &lt;enumeration value="MOP"/>
 *     &lt;enumeration value="MRO"/>
 *     &lt;enumeration value="MTL"/>
 *     &lt;enumeration value="MUR"/>
 *     &lt;enumeration value="MVR"/>
 *     &lt;enumeration value="MWK"/>
 *     &lt;enumeration value="MXN"/>
 *     &lt;enumeration value="MYR"/>
 *     &lt;enumeration value="MZM"/>
 *     &lt;enumeration value="NAD"/>
 *     &lt;enumeration value="NGN"/>
 *     &lt;enumeration value="NIO"/>
 *     &lt;enumeration value="NOK"/>
 *     &lt;enumeration value="NPR"/>
 *     &lt;enumeration value="NZD"/>
 *     &lt;enumeration value="OMR"/>
 *     &lt;enumeration value="PAB"/>
 *     &lt;enumeration value="PEN"/>
 *     &lt;enumeration value="PGK"/>
 *     &lt;enumeration value="PHP"/>
 *     &lt;enumeration value="PKR"/>
 *     &lt;enumeration value="PLN"/>
 *     &lt;enumeration value="PYG"/>
 *     &lt;enumeration value="QAR"/>
 *     &lt;enumeration value="ROL"/>
 *     &lt;enumeration value="RUB"/>
 *     &lt;enumeration value="RWF"/>
 *     &lt;enumeration value="SAR"/>
 *     &lt;enumeration value="SBD"/>
 *     &lt;enumeration value="SCR"/>
 *     &lt;enumeration value="SDD"/>
 *     &lt;enumeration value="SEK"/>
 *     &lt;enumeration value="SGD"/>
 *     &lt;enumeration value="SHP"/>
 *     &lt;enumeration value="SIT"/>
 *     &lt;enumeration value="SKK"/>
 *     &lt;enumeration value="SLL"/>
 *     &lt;enumeration value="SOS"/>
 *     &lt;enumeration value="SRD"/>
 *     &lt;enumeration value="STD"/>
 *     &lt;enumeration value="SVC"/>
 *     &lt;enumeration value="SYP"/>
 *     &lt;enumeration value="SZL"/>
 *     &lt;enumeration value="THB"/>
 *     &lt;enumeration value="TJS"/>
 *     &lt;enumeration value="TMM"/>
 *     &lt;enumeration value="TND"/>
 *     &lt;enumeration value="TOP"/>
 *     &lt;enumeration value="TRL"/>
 *     &lt;enumeration value="TRY"/>
 *     &lt;enumeration value="TTD"/>
 *     &lt;enumeration value="TWD"/>
 *     &lt;enumeration value="TZS"/>
 *     &lt;enumeration value="UAH"/>
 *     &lt;enumeration value="UGX"/>
 *     &lt;enumeration value="USD"/>
 *     &lt;enumeration value="UYU"/>
 *     &lt;enumeration value="UZS"/>
 *     &lt;enumeration value="VEB"/>
 *     &lt;enumeration value="VND"/>
 *     &lt;enumeration value="VUV"/>
 *     &lt;enumeration value="WST"/>
 *     &lt;enumeration value="XAF"/>
 *     &lt;enumeration value="XCD"/>
 *     &lt;enumeration value="XOF"/>
 *     &lt;enumeration value="XPF"/>
 *     &lt;enumeration value="XTS"/>
 *     &lt;enumeration value="XXX"/>
 *     &lt;enumeration value="YER"/>
 *     &lt;enumeration value="ZAR"/>
 *     &lt;enumeration value="ZMK"/>
 *     &lt;enumeration value="ZWD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CurrencyCode")
@XmlEnum
public enum CurrencyCode {


    /**
     * Afghanistan: Afghani
     * 
     */
    AFN,

    /**
     * Albanien: Lek
     * 
     */
    ALL,

    /**
     * Armenien: Dram
     * 
     */
    AMD,

    /**
     * Niederländische Antillen: Gulden
     * 
     */
    ANG,

    /**
     * Angola: Kwanza
     * 
     */
    AOA,

    /**
     * Argentinien: Peso
     * 
     */
    ARS,

    /**
     * Australien: Dollar
     * 
     */
    AUD,

    /**
     * Aruba: Florin
     * 
     */
    AWG,

    /**
     * Aserbaidschan: Manat
     * 
     */
    AZM,

    /**
     * Bosnien und Herzegowina: Konvertible Mark
     * 
     */
    BAM,

    /**
     * Barbados: Dollar
     * 
     */
    BBD,

    /**
     * Bangladesch: Taka
     * 
     */
    BDT,

    /**
     * Bulgarien: Lew
     * 
     */
    BGN,

    /**
     * Bahrain: Dinar
     * 
     */
    BHD,

    /**
     * Bermuda: Dollar
     * 
     */
    BMD,

    /**
     * Brunei: Dollar
     * 
     */
    BND,

    /**
     * Bolivien: Boliviano
     * 
     */
    BOB,

    /**
     * Brasilien: Real
     * 
     */
    BRL,

    /**
     * Bahamas: Dollar
     * 
     */
    BSD,

    /**
     * Bhutan: Ngultrum
     * 
     */
    BTN,

    /**
     * Botswana: Pula
     * 
     */
    BWP,

    /**
     * Weißrussland (Belarus): Rubel
     * 
     */
    BYR,

    /**
     * Belize: Dollar
     * 
     */
    BZD,

    /**
     * Kanada: Dollar
     * 
     */
    CAD,

    /**
     * Demokratische Republik Kongo: Franc
     * 
     */
    CDF,

    /**
     * Schweiz: Franken
     * 
     */
    CHF,

    /**
     * Chile: Peso
     * 
     */
    CLP,

    /**
     * China (Volksrepublik): Renminbi Yuan
     * 
     */
    CNY,

    /**
     * Kolumbien: Peso
     * 
     */
    COP,

    /**
     * Costa Rica: Colón
     * 
     */
    CRC,

    /**
     * Serbien: Dinar
     * 
     */
    CSD,

    /**
     * Kuba: Peso
     * 
     */
    CUP,

    /**
     * Kap Verde: Escudo
     * 
     */
    CVE,

    /**
     * Zypern (griechischer Teil): Pfund
     * 
     */
    CYP,

    /**
     * Tschechien: Krone
     * 
     */
    CZK,

    /**
     * Dschibuti: Franc
     * 
     */
    DJV,

    /**
     * Dänemark: Krone
     * 
     */
    DKK,

    /**
     * Dominikanische Republik: Peso
     * 
     */
    DOP,

    /**
     * Algerien: Dinar
     * 
     */
    DZD,

    /**
     * Ecuador (bis 2000): Sucre
     * 
     */
    ECS,

    /**
     * Estland: Krone
     * 
     */
    EEK,

    /**
     * Ägypten: Pfund
     * 
     */
    EGP,

    /**
     * Äthiopien: Birr
     * 
     */
    ETB,

    /**
     * Europäische Währungsunion: Euro
     * 
     */
    EUR,

    /**
     * Fidschi: Dollar
     * 
     */
    FJD,

    /**
     * Falklandinseln: Pfund
     * 
     */
    FKP,

    /**
     * Vereinigtes Königreich: Pfund
     * 
     */
    GBP,

    /**
     * Georgien: Lari
     * 
     */
    GEL,

    /**
     * Ghana: Cedi
     * 
     */
    GHC,

    /**
     * Gibraltar: Pfund
     * 
     */
    GIP,

    /**
     * Gambia: Dalasi
     * 
     */
    GMD,

    /**
     * Guinea: Franc
     * 
     */
    GNF,

    /**
     * Guatemala: Quetzal
     * 
     */
    GTQ,

    /**
     * Guyana: Dollar
     * 
     */
    GYD,

    /**
     * Hongkong: Dollar
     * 
     */
    HKD,

    /**
     * Honduras: Lempira
     * 
     */
    HNL,

    /**
     * Kroatien: Kuna
     * 
     */
    HRK,

    /**
     * Haiti: Gourde
     * 
     */
    HTG,

    /**
     * Ungarn: Forint
     * 
     */
    HUF,

    /**
     * Indonesien: Rupiah
     * 
     */
    IDR,

    /**
     * Israel: Schekel
     * 
     */
    ILS,

    /**
     * Indien: Rupie
     * 
     */
    INR,

    /**
     * Irak: Dinar
     * 
     */
    IQD,

    /**
     * Iran: Rial
     * 
     */
    IRR,

    /**
     * Island: Krone
     * 
     */
    ISK,

    /**
     * Jamaika: Dollar
     * 
     */
    JMD,

    /**
     * Jordanien: Dinar
     * 
     */
    JOD,

    /**
     * Japan: Yen
     * 
     */
    JPY,

    /**
     * Kenia: Schilling
     * 
     */
    KES,

    /**
     * Kirgisistan: Som
     * 
     */
    KGS,

    /**
     * Kambodscha: Riel
     * 
     */
    KHR,

    /**
     * Komoren: Franc
     * 
     */
    KMF,

    /**
     * Nordkorea: Won
     * 
     */
    KPW,

    /**
     * Südkorea: Won
     * 
     */
    KRW,

    /**
     * Kuwait: Dinar
     * 
     */
    KWD,

    /**
     * Kaimaninseln: Dollar
     * 
     */
    KYD,

    /**
     * Kasachstan: Tenge
     * 
     */
    KZT,

    /**
     * Laos: Kip
     * 
     */
    LAK,

    /**
     * Libanon: Pfund
     * 
     */
    LBP,

    /**
     * Sri Lanka: Rupie
     * 
     */
    LKR,

    /**
     * Liberia: Dollar
     * 
     */
    LRD,

    /**
     * Lesotho: Loti
     * 
     */
    LSL,

    /**
     * Litauen: Litas
     * 
     */
    LTL,

    /**
     * Lettland: Lats
     * 
     */
    LVL,

    /**
     * Libyen: Dinar
     * 
     */
    LYD,

    /**
     * Marokko: Dirham
     * 
     */
    MAD,

    /**
     * Moldawien: Leu
     * 
     */
    MDL,

    /**
     * Madagaskar: Franc
     * 
     */
    MGF,

    /**
     * Mazedonien: Denar
     * 
     */
    MKD,

    /**
     * Myanmar: Kyat
     * 
     */
    MMK,

    /**
     * Mongolei: Tugrik
     * 
     */
    MNT,

    /**
     * Macau: Pataca
     * 
     */
    MOP,

    /**
     * Mauretanien: Ouguiya
     * 
     */
    MRO,

    /**
     * Malta: Lira
     * 
     */
    MTL,

    /**
     * Mauritius: Rupie
     * 
     */
    MUR,

    /**
     * Malediven: Rufiyaa
     * 
     */
    MVR,

    /**
     * Malawi: Kwacha
     * 
     */
    MWK,

    /**
     * Mexiko: Peso
     * 
     */
    MXN,

    /**
     * Malaysia: Ringgit
     * 
     */
    MYR,

    /**
     * Mosambik: Metical
     * 
     */
    MZM,

    /**
     * Namibia: Dollar
     * 
     */
    NAD,

    /**
     * Nigeria: Naira
     * 
     */
    NGN,

    /**
     * Nicaragua: Cordoba Oro
     * 
     */
    NIO,

    /**
     * Norwegen: Krone
     * 
     */
    NOK,

    /**
     * Nepal: Rupie
     * 
     */
    NPR,

    /**
     * Neuseeland: Dollar
     * 
     */
    NZD,

    /**
     * Oman: Rial
     * 
     */
    OMR,

    /**
     * Panama: Balboa
     * 
     */
    PAB,

    /**
     * Peru: Nuevo Sol
     * 
     */
    PEN,

    /**
     * Papua-Neuguinea: Kina
     * 
     */
    PGK,

    /**
     * Philippinen: Peso
     * 
     */
    PHP,

    /**
     * Pakistan: Rupie
     * 
     */
    PKR,

    /**
     * Polen: Zloty
     * 
     */
    PLN,

    /**
     * Paraguay: Guaraní
     * 
     */
    PYG,

    /**
     * Katar: Riyal
     * 
     */
    QAR,

    /**
     * Rumänien: Leu
     * 
     */
    ROL,

    /**
     * Russland: Rubel
     * 
     */
    RUB,

    /**
     * Ruanda: Franc
     * 
     */
    RWF,

    /**
     * Saudi-Arabien: Riyal
     * 
     */
    SAR,

    /**
     * Salomonen: Dollar
     * 
     */
    SBD,

    /**
     * Seychellen: Rupie
     * 
     */
    SCR,

    /**
     * Sudan: Dinar
     * 
     */
    SDD,

    /**
     * Schweden: Krone
     * 
     */
    SEK,

    /**
     * Singapur: Dollar
     * 
     */
    SGD,

    /**
     * St. Helena: Pfund
     * 
     */
    SHP,

    /**
     * Slowenien: Tolar
     * 
     */
    SIT,

    /**
     * Slowakei: Krone
     * 
     */
    SKK,

    /**
     * Sierra Leone: Leone
     * 
     */
    SLL,

    /**
     * Somalia: Schilling
     * 
     */
    SOS,

    /**
     * Suriname: Dollar
     * 
     */
    SRD,

    /**
     * São Tomé und Príncipe: Dobra
     * 
     */
    STD,

    /**
     * El Salvador: Colón
     * 
     */
    SVC,

    /**
     * Syrien: Pfund
     * 
     */
    SYP,

    /**
     * Swasiland: Lilangeni
     * 
     */
    SZL,

    /**
     * Thailand: Baht
     * 
     */
    THB,

    /**
     * Tadschikistan: Somoni
     * 
     */
    TJS,

    /**
     * Turkmenistan: Manat
     * 
     */
    TMM,

    /**
     * Tunesien: Dinar
     * 
     */
    TND,

    /**
     * Tonga: Pa'anga
     * 
     */
    TOP,

    /**
     * Türkei: Lira
     * 
     */
    TRL,

    /**
     * Türkei: Neue Lira (ab 2005)
     * 
     */
    TRY,

    /**
     * Trinidad und Tobago: Dollar
     * 
     */
    TTD,

    /**
     * Taiwan: Dollar
     * 
     */
    TWD,

    /**
     * Tansania: Schilling
     * 
     */
    TZS,

    /**
     * Ukraine: Hrywnja
     * 
     */
    UAH,

    /**
     * Uganda: Shilling
     * 
     */
    UGX,

    /**
     * USA: Dollar
     * 
     */
    USD,

    /**
     * Uruguay: Peso
     * 
     */
    UYU,

    /**
     * Usbekistan: Sum
     * 
     */
    UZS,

    /**
     * Venezuela: Bolivar
     * 
     */
    VEB,

    /**
     * Vietnam: Dong
     * 
     */
    VND,

    /**
     * Vanuatu: Vatu
     * 
     */
    VUV,

    /**
     * Samoa: Tala
     * 
     */
    WST,

    /**
     * Zentralafrikanische Wirtschafts- und Währungsunion: CFA-Franc
     * 
     */
    XAF,

    /**
     * Ostkaribische Währungsunion: Dollar
     * 
     */
    XCD,

    /**
     * Westafrikanische Wirtschafts- und Währungsunion: CFA-Franc
     * 
     */
    XOF,

    /**
     * Neukaledonien: CFP-Franc
     * 
     */
    XPF,

    /**
     * Spezialcode für Testzwecke; keine existierende Währung
     * 
     */
    XTS,

    /**
     * keine Währung
     * 
     */
    XXX,

    /**
     * Jemen: Rial
     * 
     */
    YER,

    /**
     * Südafrika: Rand
     * 
     */
    ZAR,

    /**
     * Sambia: Kwacha
     * 
     */
    ZMK,

    /**
     * Simbabwe: Dollar
     * 
     */
    ZWD;

    public String value() {
        return name();
    }

    public static CurrencyCode fromValue(String v) {
        return valueOf(v);
    }

}
