//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * Data type for the modelling of information regarding the encryption of signature and order data.
 * 
 * <p>Java class for DataEncryptionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataEncryptionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EncryptionPubKeyDigest">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:org:ebics:H004>PubKeyDigestType">
 *                 &lt;attribute name="Version" use="required" type="{urn:org:ebics:H004}EncryptionVersionType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TransactionKey" type="{urn:org:ebics:H004}SymmetricKeyType"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataEncryptionInfoType", propOrder = {
    "encryptionPubKeyDigest",
    "transactionKey",
    "any"
})
@XmlSeeAlso({
    tech.libeufin.messages.ebics.response.DataTransferRequestType.DataEncryptionInfo.class,
    tech.libeufin.messages.ebics.response.DataTransferResponseType.DataEncryptionInfo.class
})
public class DataEncryptionInfoType {

    @XmlElement(name = "EncryptionPubKeyDigest", required = true)
    protected DataEncryptionInfoType.EncryptionPubKeyDigest encryptionPubKeyDigest;
    @XmlElement(name = "TransactionKey", required = true)
    protected byte[] transactionKey;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the encryptionPubKeyDigest property.
     * 
     * @return
     *     possible object is
     *     {@link DataEncryptionInfoType.EncryptionPubKeyDigest }
     *     
     */
    public DataEncryptionInfoType.EncryptionPubKeyDigest getEncryptionPubKeyDigest() {
        return encryptionPubKeyDigest;
    }

    /**
     * Sets the value of the encryptionPubKeyDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataEncryptionInfoType.EncryptionPubKeyDigest }
     *     
     */
    public void setEncryptionPubKeyDigest(DataEncryptionInfoType.EncryptionPubKeyDigest value) {
        this.encryptionPubKeyDigest = value;
    }

    /**
     * Gets the value of the transactionKey property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getTransactionKey() {
        return transactionKey;
    }

    /**
     * Sets the value of the transactionKey property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setTransactionKey(byte[] value) {
        this.transactionKey = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:org:ebics:H004>PubKeyDigestType">
     *       &lt;attribute name="Version" use="required" type="{urn:org:ebics:H004}EncryptionVersionType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EncryptionPubKeyDigest
        extends PubKeyDigestType
    {

        @XmlAttribute(name = "Version", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String version;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }

}
