//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Order type for order data H3K (request: initialise all three user's keys).
 * 
 * <p>Java class for H3KRequestOrderDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="H3KRequestOrderDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SignatureCertificateInfo" type="{urn:org:ebics:H004}SignatureCertificateInfoType"/>
 *         &lt;element name="AuthenticationCertificateInfo" type="{urn:org:ebics:H004}AuthenticationCertificateInfoType"/>
 *         &lt;element name="EncryptionCertificateInfo" type="{urn:org:ebics:H004}EncryptionCertificateInfoType"/>
 *         &lt;element name="PartnerID" type="{urn:org:ebics:H004}PartnerIDType"/>
 *         &lt;element name="UserID" type="{urn:org:ebics:H004}UserIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "H3KRequestOrderDataType", propOrder = {
    "signatureCertificateInfo",
    "authenticationCertificateInfo",
    "encryptionCertificateInfo",
    "partnerID",
    "userID"
})
public class H3KRequestOrderDataType {

    @XmlElement(name = "SignatureCertificateInfo", required = true)
    protected SignatureCertificateInfoType signatureCertificateInfo;
    @XmlElement(name = "AuthenticationCertificateInfo", required = true)
    protected AuthenticationCertificateInfoType authenticationCertificateInfo;
    @XmlElement(name = "EncryptionCertificateInfo", required = true)
    protected EncryptionCertificateInfoType encryptionCertificateInfo;
    @XmlElement(name = "PartnerID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String partnerID;
    @XmlElement(name = "UserID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String userID;

    /**
     * Gets the value of the signatureCertificateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureCertificateInfoType }
     *     
     */
    public SignatureCertificateInfoType getSignatureCertificateInfo() {
        return signatureCertificateInfo;
    }

    /**
     * Sets the value of the signatureCertificateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureCertificateInfoType }
     *     
     */
    public void setSignatureCertificateInfo(SignatureCertificateInfoType value) {
        this.signatureCertificateInfo = value;
    }

    /**
     * Gets the value of the authenticationCertificateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationCertificateInfoType }
     *     
     */
    public AuthenticationCertificateInfoType getAuthenticationCertificateInfo() {
        return authenticationCertificateInfo;
    }

    /**
     * Sets the value of the authenticationCertificateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationCertificateInfoType }
     *     
     */
    public void setAuthenticationCertificateInfo(AuthenticationCertificateInfoType value) {
        this.authenticationCertificateInfo = value;
    }

    /**
     * Gets the value of the encryptionCertificateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptionCertificateInfoType }
     *     
     */
    public EncryptionCertificateInfoType getEncryptionCertificateInfo() {
        return encryptionCertificateInfo;
    }

    /**
     * Sets the value of the encryptionCertificateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptionCertificateInfoType }
     *     
     */
    public void setEncryptionCertificateInfo(EncryptionCertificateInfoType value) {
        this.encryptionCertificateInfo = value;
    }

    /**
     * Gets the value of the partnerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerID() {
        return partnerID;
    }

    /**
     * Sets the value of the partnerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerID(String value) {
        this.partnerID = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

}
