//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * Data type for HPD's parameters regarding the EBICS protocol.
 * 
 * <p>Java class for HPDProtocolParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HPDProtocolParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{urn:org:ebics:H004}HPDVersionType"/>
 *         &lt;element name="Recovery" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
 *                 &lt;anyAttribute namespace='urn:org:ebics:H004'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PreValidation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
 *                 &lt;anyAttribute namespace='urn:org:ebics:H004'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="X509Data" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
 *                 &lt;attribute name="persistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;anyAttribute namespace='urn:org:ebics:H004'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ClientDataDownload" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
 *                 &lt;anyAttribute namespace='urn:org:ebics:H004'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DownloadableOrderData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
 *                 &lt;anyAttribute namespace='urn:org:ebics:H004'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HPDProtocolParamsType", propOrder = {
    "version",
    "recovery",
    "preValidation",
    "x509Data",
    "clientDataDownload",
    "downloadableOrderData",
    "any"
})
public class HPDProtocolParamsType {

    @XmlElement(name = "Version", required = true)
    protected HPDVersionType version;
    @XmlElement(name = "Recovery")
    protected HPDProtocolParamsType.Recovery recovery;
    @XmlElement(name = "PreValidation")
    protected HPDProtocolParamsType.PreValidation preValidation;
    @XmlElement(name = "X509Data")
    protected HPDProtocolParamsType.X509Data x509Data;
    @XmlElement(name = "ClientDataDownload")
    protected HPDProtocolParamsType.ClientDataDownload clientDataDownload;
    @XmlElement(name = "DownloadableOrderData")
    protected HPDProtocolParamsType.DownloadableOrderData downloadableOrderData;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link HPDVersionType }
     *     
     */
    public HPDVersionType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDVersionType }
     *     
     */
    public void setVersion(HPDVersionType value) {
        this.version = value;
    }

    /**
     * Gets the value of the recovery property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType.Recovery }
     *     
     */
    public HPDProtocolParamsType.Recovery getRecovery() {
        return recovery;
    }

    /**
     * Sets the value of the recovery property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType.Recovery }
     *     
     */
    public void setRecovery(HPDProtocolParamsType.Recovery value) {
        this.recovery = value;
    }

    /**
     * Gets the value of the preValidation property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType.PreValidation }
     *     
     */
    public HPDProtocolParamsType.PreValidation getPreValidation() {
        return preValidation;
    }

    /**
     * Sets the value of the preValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType.PreValidation }
     *     
     */
    public void setPreValidation(HPDProtocolParamsType.PreValidation value) {
        this.preValidation = value;
    }

    /**
     * Gets the value of the x509Data property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType.X509Data }
     *     
     */
    public HPDProtocolParamsType.X509Data getX509Data() {
        return x509Data;
    }

    /**
     * Sets the value of the x509Data property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType.X509Data }
     *     
     */
    public void setX509Data(HPDProtocolParamsType.X509Data value) {
        this.x509Data = value;
    }

    /**
     * Gets the value of the clientDataDownload property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType.ClientDataDownload }
     *     
     */
    public HPDProtocolParamsType.ClientDataDownload getClientDataDownload() {
        return clientDataDownload;
    }

    /**
     * Sets the value of the clientDataDownload property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType.ClientDataDownload }
     *     
     */
    public void setClientDataDownload(HPDProtocolParamsType.ClientDataDownload value) {
        this.clientDataDownload = value;
    }

    /**
     * Gets the value of the downloadableOrderData property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType.DownloadableOrderData }
     *     
     */
    public HPDProtocolParamsType.DownloadableOrderData getDownloadableOrderData() {
        return downloadableOrderData;
    }

    /**
     * Sets the value of the downloadableOrderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType.DownloadableOrderData }
     *     
     */
    public void setDownloadableOrderData(HPDProtocolParamsType.DownloadableOrderData value) {
        this.downloadableOrderData = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
     *       &lt;anyAttribute namespace='urn:org:ebics:H004'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ClientDataDownload {

        @XmlAttribute(name = "supported")
        protected Boolean supported;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the supported property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSupported() {
            if (supported == null) {
                return true;
            } else {
                return supported;
            }
        }

        /**
         * Sets the value of the supported property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSupported(Boolean value) {
            this.supported = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
     *       &lt;anyAttribute namespace='urn:org:ebics:H004'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DownloadableOrderData {

        @XmlAttribute(name = "supported")
        protected Boolean supported;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the supported property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSupported() {
            if (supported == null) {
                return true;
            } else {
                return supported;
            }
        }

        /**
         * Sets the value of the supported property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSupported(Boolean value) {
            this.supported = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * Optional support flag, default = true.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
     *       &lt;anyAttribute namespace='urn:org:ebics:H004'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PreValidation {

        @XmlAttribute(name = "supported")
        protected Boolean supported;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the supported property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSupported() {
            if (supported == null) {
                return true;
            } else {
                return supported;
            }
        }

        /**
         * Sets the value of the supported property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSupported(Boolean value) {
            this.supported = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
     *       &lt;anyAttribute namespace='urn:org:ebics:H004'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Recovery {

        @XmlAttribute(name = "supported")
        protected Boolean supported;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the supported property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSupported() {
            if (supported == null) {
                return true;
            } else {
                return supported;
            }
        }

        /**
         * Sets the value of the supported property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSupported(Boolean value) {
            this.supported = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}OptSupportFlag"/>
     *       &lt;attribute name="persistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;anyAttribute namespace='urn:org:ebics:H004'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class X509Data {

        @XmlAttribute(name = "persistent")
        protected Boolean persistent;
        @XmlAttribute(name = "supported")
        protected Boolean supported;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the persistent property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPersistent() {
            if (persistent == null) {
                return false;
            } else {
                return persistent;
            }
        }

        /**
         * Sets the value of the persistent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPersistent(Boolean value) {
            this.persistent = value;
        }

        /**
         * Gets the value of the supported property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isSupported() {
            if (supported == null) {
                return true;
            } else {
                return supported;
            }
        }

        /**
         * Sets the value of the supported property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSupported(Boolean value) {
            this.supported = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
