//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 11:07:53 AM CEST 
//


package tech.libeufin.messages.ebics.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * Datentyp für Auftragsdaten für Auftragsart HVS (Anfrage: VEU-Storno).
 * 
 * <p>Java class for HVSRequestOrderDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HVSRequestOrderDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CancelledDataDigest" type="{urn:org:ebics:H004}DataDigestType"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HVSRequestOrderDataType", propOrder = {
    "cancelledDataDigest",
    "any"
})
public class HVSRequestOrderDataType {

    @XmlElement(name = "CancelledDataDigest", required = true)
    protected DataDigestType cancelledDataDigest;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the cancelledDataDigest property.
     * 
     * @return
     *     possible object is
     *     {@link DataDigestType }
     *     
     */
    public DataDigestType getCancelledDataDigest() {
        return cancelledDataDigest;
    }

    /**
     * Sets the value of the cancelledDataDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataDigestType }
     *     
     */
    public void setCancelledDataDigest(DataDigestType value) {
        this.cancelledDataDigest = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
