//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.18 at 06:44:54 PM CEST 
//


package tech.libeufin.messages.ebics.keyresponse;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * Datentyp für den Transfer von Auftragsdaten (Anfrage).
 * 
 * <p>Java class for DataTransferRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataTransferRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="DataEncryptionInfo">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;extension base="{urn:org:ebics:H004}DataEncryptionInfoType">
 *                     &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
 *                   &lt;/extension>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *             &lt;element name="SignatureData">
 *               &lt;complexType>
 *                 &lt;simpleContent>
 *                   &lt;extension base="&lt;urn:org:ebics:H004>SignatureDataType">
 *                     &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
 *                   &lt;/extension>
 *                 &lt;/simpleContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="OrderData">
 *               &lt;complexType>
 *                 &lt;simpleContent>
 *                   &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
 *                     &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
 *                   &lt;/extension>
 *                 &lt;/simpleContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataTransferRequestType", propOrder = {
    "dataEncryptionInfo",
    "signatureData",
    "orderData",
    "any"
})
public class DataTransferRequestType {

    @XmlElement(name = "DataEncryptionInfo")
    protected DataTransferRequestType.DataEncryptionInfo dataEncryptionInfo;
    @XmlElement(name = "SignatureData")
    protected DataTransferRequestType.SignatureData signatureData;
    @XmlElement(name = "OrderData")
    protected DataTransferRequestType.OrderData orderData;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the dataEncryptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DataTransferRequestType.DataEncryptionInfo }
     *     
     */
    public DataTransferRequestType.DataEncryptionInfo getDataEncryptionInfo() {
        return dataEncryptionInfo;
    }

    /**
     * Sets the value of the dataEncryptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTransferRequestType.DataEncryptionInfo }
     *     
     */
    public void setDataEncryptionInfo(DataTransferRequestType.DataEncryptionInfo value) {
        this.dataEncryptionInfo = value;
    }

    /**
     * Gets the value of the signatureData property.
     * 
     * @return
     *     possible object is
     *     {@link DataTransferRequestType.SignatureData }
     *     
     */
    public DataTransferRequestType.SignatureData getSignatureData() {
        return signatureData;
    }

    /**
     * Sets the value of the signatureData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTransferRequestType.SignatureData }
     *     
     */
    public void setSignatureData(DataTransferRequestType.SignatureData value) {
        this.signatureData = value;
    }

    /**
     * Gets the value of the orderData property.
     * 
     * @return
     *     possible object is
     *     {@link DataTransferRequestType.OrderData }
     *     
     */
    public DataTransferRequestType.OrderData getOrderData() {
        return orderData;
    }

    /**
     * Sets the value of the orderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTransferRequestType.OrderData }
     *     
     */
    public void setOrderData(DataTransferRequestType.OrderData value) {
        this.orderData = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:org:ebics:H004}DataEncryptionInfoType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DataEncryptionInfo
        extends DataEncryptionInfoType
    {

        @XmlAttribute(name = "authenticate", required = true)
        protected boolean authenticate;

        /**
         * Gets the value of the authenticate property.
         * 
         */
        public boolean isAuthenticate() {
            return authenticate;
        }

        /**
         * Sets the value of the authenticate property.
         * 
         */
        public void setAuthenticate(boolean value) {
            this.authenticate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
     *       &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OrderData {

        @XmlValue
        protected byte[] value;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Datentyp für binäre Auftragsdaten (komprimiert, verschlüsselt und kodiert).
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:org:ebics:H004>SignatureDataType">
     *       &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SignatureData {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "authenticate", required = true)
        protected boolean authenticate;

        /**
         * Datentyp für binäre Signaturdaten (komprimiert, verschlüsselt und kodiert).
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the authenticate property.
         * 
         */
        public boolean isAuthenticate() {
            return authenticate;
        }

        /**
         * Sets the value of the authenticate property.
         * 
         */
        public void setAuthenticate(boolean value) {
            this.authenticate = value;
        }

    }

}
