//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.18 at 06:44:54 PM CEST 
//


package tech.libeufin.messages.ebics.keyresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Datentyp für Auftragsdaten für Auftragsart HPD (Antwort: Bankparameter abholen).
 * 
 * <p>Java class for HPDResponseOrderDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HPDResponseOrderDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccessParams" type="{urn:org:ebics:H004}HPDAccessParamsType"/>
 *         &lt;element name="ProtocolParams" type="{urn:org:ebics:H004}HPDProtocolParamsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HPDResponseOrderDataType", propOrder = {
    "accessParams",
    "protocolParams"
})
public class HPDResponseOrderDataType {

    @XmlElement(name = "AccessParams", required = true)
    protected HPDAccessParamsType accessParams;
    @XmlElement(name = "ProtocolParams", required = true)
    protected HPDProtocolParamsType protocolParams;

    /**
     * Gets the value of the accessParams property.
     * 
     * @return
     *     possible object is
     *     {@link HPDAccessParamsType }
     *     
     */
    public HPDAccessParamsType getAccessParams() {
        return accessParams;
    }

    /**
     * Sets the value of the accessParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDAccessParamsType }
     *     
     */
    public void setAccessParams(HPDAccessParamsType value) {
        this.accessParams = value;
    }

    /**
     * Gets the value of the protocolParams property.
     * 
     * @return
     *     possible object is
     *     {@link HPDProtocolParamsType }
     *     
     */
    public HPDProtocolParamsType getProtocolParams() {
        return protocolParams;
    }

    /**
     * Sets the value of the protocolParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link HPDProtocolParamsType }
     *     
     */
    public void setProtocolParams(HPDProtocolParamsType value) {
        this.protocolParams = value;
    }

}
