//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 06:36:01 PM CEST 
//


package tech.libeufin.messages.ebics.keyrequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountHolderRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccountHolderRoleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Originator"/>
 *     &lt;enumeration value="Recipient"/>
 *     &lt;enumeration value="Presenter"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AccountHolderRoleType")
@XmlEnum
public enum AccountHolderRoleType {


    /**
     * Auftraggeber
     * 
     */
    @XmlEnumValue("Originator")
    ORIGINATOR("Originator"),

    /**
     * Empfänger
     * 
     */
    @XmlEnumValue("Recipient")
    RECIPIENT("Recipient"),

    /**
     * Überbringer, Einreicher
     * 
     */
    @XmlEnumValue("Presenter")
    PRESENTER("Presenter"),

    /**
     * andere Rolle
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    AccountHolderRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccountHolderRoleType fromValue(String v) {
        for (AccountHolderRoleType c: AccountHolderRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
