//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 06:36:01 PM CEST 
//


package tech.libeufin.messages.ebics.keyrequest;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="static" type="{urn:org:ebics:H004}UnsecuredRequestStaticHeaderType"/>
 *                   &lt;element name="mutable" type="{urn:org:ebics:H004}EmptyMutableHeaderType"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataTransfer">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OrderData">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
 *                                     &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:org:ebics:H004}VersionAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "ebicsUnsecuredRequest")
public class EbicsUnsecuredRequest {

    @XmlElement(required = true)
    protected EbicsUnsecuredRequest.Header header;
    @XmlElement(required = true)
    protected EbicsUnsecuredRequest.Body body;
    @XmlAttribute(name = "Version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "Revision")
    protected Integer revision;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link EbicsUnsecuredRequest.Header }
     *     
     */
    public EbicsUnsecuredRequest.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link EbicsUnsecuredRequest.Header }
     *     
     */
    public void setHeader(EbicsUnsecuredRequest.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link EbicsUnsecuredRequest.Body }
     *     
     */
    public EbicsUnsecuredRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link EbicsUnsecuredRequest.Body }
     *     
     */
    public void setBody(EbicsUnsecuredRequest.Body value) {
        this.body = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRevision(Integer value) {
        this.revision = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataTransfer">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OrderData">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
     *                           &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataTransfer"
    })
    public static class Body {

        @XmlElement(name = "DataTransfer", required = true)
        protected EbicsUnsecuredRequest.Body.DataTransfer dataTransfer;

        /**
         * Gets the value of the dataTransfer property.
         * 
         * @return
         *     possible object is
         *     {@link EbicsUnsecuredRequest.Body.DataTransfer }
         *     
         */
        public EbicsUnsecuredRequest.Body.DataTransfer getDataTransfer() {
            return dataTransfer;
        }

        /**
         * Sets the value of the dataTransfer property.
         * 
         * @param value
         *     allowed object is
         *     {@link EbicsUnsecuredRequest.Body.DataTransfer }
         *     
         */
        public void setDataTransfer(EbicsUnsecuredRequest.Body.DataTransfer value) {
            this.dataTransfer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OrderData">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
         *                 &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orderData"
        })
        public static class DataTransfer {

            @XmlElement(name = "OrderData", required = true)
            protected EbicsUnsecuredRequest.Body.DataTransfer.OrderData orderData;

            /**
             * Gets the value of the orderData property.
             * 
             * @return
             *     possible object is
             *     {@link EbicsUnsecuredRequest.Body.DataTransfer.OrderData }
             *     
             */
            public EbicsUnsecuredRequest.Body.DataTransfer.OrderData getOrderData() {
                return orderData;
            }

            /**
             * Sets the value of the orderData property.
             * 
             * @param value
             *     allowed object is
             *     {@link EbicsUnsecuredRequest.Body.DataTransfer.OrderData }
             *     
             */
            public void setOrderData(EbicsUnsecuredRequest.Body.DataTransfer.OrderData value) {
                this.orderData = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;urn:org:ebics:H004>OrderDataType">
             *       &lt;anyAttribute processContents='lax' namespace='urn:org:ebics:H004'/>
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class OrderData {

                @XmlValue
                protected byte[] value;
                @XmlAnyAttribute
                private Map<QName, String> otherAttributes = new HashMap<QName, String>();

                /**
                 * Datentyp für binäre Auftragsdaten (komprimiert, verschlüsselt und kodiert).
                 * 
                 * @return
                 *     possible object is
                 *     byte[]
                 */
                public byte[] getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     byte[]
                 */
                public void setValue(byte[] value) {
                    this.value = value;
                }

                /**
                 * Gets a map that contains attributes that aren't bound to any typed property on this class.
                 * 
                 * <p>
                 * the map is keyed by the name of the attribute and 
                 * the value is the string value of the attribute.
                 * 
                 * the map returned by this method is live, and you can add new attribute
                 * by updating the map directly. Because of this design, there's no setter.
                 * 
                 * 
                 * @return
                 *     always non-null
                 */
                public Map<QName, String> getOtherAttributes() {
                    return otherAttributes;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="static" type="{urn:org:ebics:H004}UnsecuredRequestStaticHeaderType"/>
     *         &lt;element name="mutable" type="{urn:org:ebics:H004}EmptyMutableHeaderType"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{urn:org:ebics:H004}AuthenticationMarker"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_static",
        "mutable"
    })
    public static class Header {

        @XmlElement(name = "static", required = true)
        protected UnsecuredRequestStaticHeaderType _static;
        @XmlElement(required = true)
        protected EmptyMutableHeaderType mutable;
        @XmlAttribute(name = "authenticate", required = true)
        protected boolean authenticate;

        /**
         * Gets the value of the static property.
         * 
         * @return
         *     possible object is
         *     {@link UnsecuredRequestStaticHeaderType }
         *     
         */
        public UnsecuredRequestStaticHeaderType getStatic() {
            return _static;
        }

        /**
         * Sets the value of the static property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnsecuredRequestStaticHeaderType }
         *     
         */
        public void setStatic(UnsecuredRequestStaticHeaderType value) {
            this._static = value;
        }

        /**
         * Gets the value of the mutable property.
         * 
         * @return
         *     possible object is
         *     {@link EmptyMutableHeaderType }
         *     
         */
        public EmptyMutableHeaderType getMutable() {
            return mutable;
        }

        /**
         * Sets the value of the mutable property.
         * 
         * @param value
         *     allowed object is
         *     {@link EmptyMutableHeaderType }
         *     
         */
        public void setMutable(EmptyMutableHeaderType value) {
            this.mutable = value;
        }

        /**
         * Gets the value of the authenticate property.
         * 
         */
        public boolean isAuthenticate() {
            return authenticate;
        }

        /**
         * Sets the value of the authenticate property.
         * 
         */
        public void setAuthenticate(boolean value) {
            this.authenticate = value;
        }

    }

}
