//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 06:36:01 PM CEST 
//


package tech.libeufin.messages.ebics.keyrequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * Datentyp für HPD-Versionsinformationen.
 * 
 * <p>Java class for HPDVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HPDVersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Protocol">
 *           &lt;simpleType>
 *             &lt;list itemType="{urn:org:ebics:H004}ProtocolVersionType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Authentication">
 *           &lt;simpleType>
 *             &lt;list itemType="{urn:org:ebics:H004}AuthenticationVersionType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Encryption">
 *           &lt;simpleType>
 *             &lt;list itemType="{urn:org:ebics:H004}EncryptionVersionType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Signature">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.ebics.org/S001}SignatureVersionType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HPDVersionType", propOrder = {
    "protocol",
    "authentication",
    "encryption",
    "signature",
    "any"
})
public class HPDVersionType {

    @XmlList
    @XmlElement(name = "Protocol", required = true)
    protected List<String> protocol;
    @XmlList
    @XmlElement(name = "Authentication", required = true)
    protected List<String> authentication;
    @XmlList
    @XmlElement(name = "Encryption", required = true)
    protected List<String> encryption;
    @XmlList
    @XmlElement(name = "Signature", required = true)
    protected List<String> signature;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the protocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProtocol() {
        if (protocol == null) {
            protocol = new ArrayList<String>();
        }
        return this.protocol;
    }

    /**
     * Gets the value of the authentication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authentication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthentication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuthentication() {
        if (authentication == null) {
            authentication = new ArrayList<String>();
        }
        return this.authentication;
    }

    /**
     * Gets the value of the encryption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encryption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncryption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEncryption() {
        if (encryption == null) {
            encryption = new ArrayList<String>();
        }
        return this.encryption;
    }

    /**
     * Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSignature() {
        if (signature == null) {
            signature = new ArrayList<String>();
        }
        return this.signature;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
